// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"labs-four/config"
	"labs-four/internal/infra/web"
	"labs-four/internal/usecases"
)

// Injectors from wire.go:

func NewConfig() *config.AppSettings {
	appSettings := config.ProvideConfig()
	return appSettings
}

func NewGetHelloHandler() *web.GetHelloHandler {
	appSettings := config.ProvideConfig()
	helloUseCase := usecases.NewHelloUseCase(appSettings)
	getHelloHandler := web.NewGetHelloHandler(helloUseCase, appSettings)
	return getHelloHandler
}

// wire.go:

var ProviderConfig = wire.NewSet(config.ProvideConfig)

var ProviderUseCase = wire.NewSet(usecases.NewHelloUseCase, wire.Bind(new(usecases.HelloUseCaseInterface), new(*usecases.HelloUseCase)))

var ProviderHandler = wire.NewSet(web.NewGetHelloHandler)
